akka {
  cluster {
    log-info = off
#    use-dispatcher = default-dispatcher
    min-nr-of-members = 1

    failure-detector {
      # implementation-class = "akka.remote.PhiAccrualFailureDetector"
      heartbeat-interval = 1 s
      threshold = 12.0
      max-sample-size = 1000
      min-std-deviation = 400 ms
      acceptable-heartbeat-pause = 3 s
      monitored-by-nr-of-members = 3
      expected-response-after = 2 s
    }

    sharding {
      passivate-idle-entity-after = 120 s
    }

    # auto-discovery = off //TODO not recognized by Diagnostics
    seed-nodes = []
    seed-nodes = [${?SEED_NODES}]
    shutdown-after-unsuccessful-join-seed-nodes = 30s
  }

  # SBR
  #cluster.downing-provider-class = "tanukki.akka.cluster.autodown.MajorityLeaderAutoDowning"
  cluster.downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"

}

custom-downing {
    stable-after = 20s

    majority-leader-auto-downing {
      majority-member-role = ""
      down-if-in-minority = true
      shutdown-actor-system-on-resolution = true
    }
}