akka {
  cluster {
    log-info = off
    #    use-dispatcher = default-dispatcher
    min-nr-of-members = 1

    failure-detector {
      # implementation-class = "akka.remote.PhiAccrualFailureDetector"
      heartbeat-interval = 1 s
      threshold = 12.0
      max-sample-size = 1000
      min-std-deviation = 400 ms
      acceptable-heartbeat-pause = 3 s
      monitored-by-nr-of-members = 3
      expected-response-after = 2 s
    }

    sharding {
      passivate-idle-entity-after = 120 s
    }

    # auto-discovery = off //TODO not recognized by Diagnostics
    seed-nodes = []
    seed-nodes = [${?SEED_NODES}]
    shutdown-after-unsuccessful-join-seed-nodes = 30s
  }
}

#SBR Config.
akka.cluster.downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"

akka {
  cluster{
    split-brain-resolver {
      active-strategy = keep-majority
      stable-after = 20s
      down-all-when-unstable = on
      }
    }
  }

akka.coordinated-shutdown.exit-jvm = on