#!/bin/bash
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-ACTIVIDADES" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-ACTIVIDADES.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-COMPONENTE-I-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-COMPONENTE-I-TRI-ONGOING.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-CUPON-DESCUENTO-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-CUPON-DESCUENTO-TRI-ONGOING.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-DECJURADAS" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-DECJURADAS.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-DOMICILIO-OBJ-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-DOMICILIO-OBJ-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-DOMICILIO-SUJ-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-DOMICILIO-SUJ-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-ETAPROCESALES-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-ETAPROCESALES-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-JUICIOS-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-JUICIOS-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-JUICIOS-OBLIGACIONES-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-JUICIOS-TRI-OBN-ONGOING.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-JUICIOS-TRI-CAB" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-JUICIOS-TRI-CAB.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-JUICIOS-CAB-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-JUICIOS-TRI-CAB.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-PARAMPLAN-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-PARAMPLAN-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-PARAMRECARGO-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-PARAMRECARGO-ANT.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-PLANES-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-PLANES-TRI.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-SUBASTAS" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-SUBASTAS.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-TRAMITES" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/DGR-COP-TRAMITES.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-OBJETOS-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-OBJETOS-TRI-ONGOING.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-OBLIGACIONES-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-OBLIGACIONES-TRI-ONGOING.json
kafkacat -P -b 0.0.0.0:9092 -t "DGR-COP-SUJETO-TRI" /home/lautapa/Documents/PCS-SAM/pcs-sam/assets/examples/test/DGR-COP-SUJETO-TRI-ONGOING.json 
