projectionists {
    defaultParallelism = 3
    defaultParallelism = ${?PROJECTIONIST_PARALELLISM}
}

# Default persistence extension settings.
akka.persistence {
    # When starting many persistent actors at the same time the journal
    # and its data store is protected from being overloaded by limiting number
    # of recoveries that can be in progress at the same time. When
    # exceeding the limit the actors will wait until other recoveries have
    # been completed.
    #max-concurrent-recoveries = 50
    max-concurrent-recoveries = 50

    # Fully qualified class name providing a default internal stash overflow strategy.
    # It needs to be a subclass of akka.persistence.StashOverflowStrategyConfigurator.
    # The default strategy throws StashOverflowException.
    internal-stash-overflow-strategy = "akka.persistence.ThrowExceptionConfigurator"
}


#akka {
#  persistence {
#    journal.plugin = "inmemory-journal"
#    snapshot-store.plugin = "inmemory-snapshot-store"
#  }
#}


# Default reliable delivery settings.
akka.persistence.at-least-once-delivery {
    # Interval between re-delivery attempts.
    redeliver-interval = 5s
    # Maximum number of unconfirmed messages that will be sent in one
    # re-delivery burst.
    redelivery-burst-limit = 10000
    # After this number of delivery attempts a
    # `ReliableRedelivery.UnconfirmedWarning`, message will be sent to the actor.
    warn-after-number-of-unconfirmed-attempts = 5
    # Maximum number of unconfirmed messages that an actor with
    # AtLeastOnceDelivery is allowed to hold in memory.
    max-unconfirmed-messages = 100000
}



  # This is used to create the Akka actors dispatchers, who use fork join
  hardwareSpecs {

    # Min number of threads to cap factor-based parallelism number to
    parallelismMin = 8 //TODO Before 8
    # parallelismMin = ${?parallelismMin}
    # Parallelism (threads) ... ceil(available processors * factor)
    parallelismFactor = 3 //TODO Before 3
    # Max number of threads to cap factor-based parallelism number to
    parallelismMax = 21 //TODO before 64
    #parallelismMax = ${?parallelismMax}


    # Throughput defines the maximum number of messages to be
    # processed per actor before the thread jumps to the next actor.
    # Set to 1 for as fair as possible.

    #
    # There are a few edge cases.
    # If you have a case where the number of threads is equal to the number of actors
    # using the dispatcher, set the number extremely high, like 1000.

    # If your actors perform tasks that will take some time to complete
    # and you need fairness to avoid starvation of other actors sharing the pool,
    # set the throughput to 1.
    #
    processedMessagesPerActorPerThreadJump = 1 # https://letitcrash.com/post/40755146949/tuning-dispatchers-in-akka-applications

  }

  //TODO changed to see improvement in streams
  akka {
    actor {
      default-dispatcher {
        executor = "fork-join-executor"
        fork-join-executor {
          parallelism-min = 4
          parallelism-factor = 3
          parallelism-max = 24
        }
        throughput = 20
        throughput-deadline-time = 200ms
      }
    }
  }


akka.actor.default-dispatcher.thread-pool-executor.allow-core-timeout = off

  akka.actor.default-blocking-io-dispatcher {
    thread-pool-executor {
    }
  }

  my-dispatcher {
    type = "Dispatcher"
    executor = "thread-pool-executor"
    thread-pool-executor {
      core-pool-size-min = 8
      core-pool-size-max = 64
      max-pool-size-min = 50
      max-pool-size-max = 100
      task-queue-size = 20
    }
    #  throughput = 10
  }


//To Debug Kafka messages
#akka {
#  actor {
#    debug.receive = true
#  }
#  kafka.consumer {
#    poll-interval = 300ms
#  }
#}
