{
 "title": "PCS-Dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "options": {
    "content": "#                   KAFKA->WRITESIDE\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 0 },
   "options": {
    "content": "#           WRITESIDE->CASSANDRA\n\n"
   }
  },
  {
   "title": "TOTAL EVENTS PROCESSED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"DGR-COP.*-ProcessedMessagesCounter\"})\n\n"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS REJECTED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"DGR-COP.*-RejectedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS PERSISTED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\".*-persisted\"})"
    }
   ]
  },
  {
   "title": "TOTAL ERRORS ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"actor-transaction.*_transaction-error\"})"
    }
   ]
  },
  {
   "title": "Kafka Processed Messages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=~\"DGR-COP.*-ProcessedMessagesCounter\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS REQUESTS",
   "type": "graph",
   "description": "Transaction requests accumlated",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=~\"actor-transaction-.*_transaction-request\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Message consumptions per second (OPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "\nsum(irate(copernico_counters_total{entity=~\"actor-transaction-.*_transaction-request\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Request per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(copernico_counters_total{entity=~\"actor-transaction-.*_transaction-request\"}[1m]))",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Transaction Latency Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(copernico_histograms_bucket{entity=~\"actor-transaction-.*_transaction-latency\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 35 },
   "options": {
    "content": "#                    KAFKA->READSIDE\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 35 },
   "options": {
    "content": "#           READSIDE->CASSANDRA\n\n"
   }
  },
  {
   "title": "TOTAL EVENTS PROCESSED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\".*SnapshotPersisted-ProcessedMessagesCounter\"})\n+\nsum(copernico_counters_total{entity=~\".*PersistedSnapshot-ProcessedMessagesCounter\"})\n"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS REJECTED ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\".*FromDto-RejectedMessagesCounter\"})"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS REQUESTED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"actor-transaction.*handler-request\"})"
    }
   ]
  },
  {
   "title": "TOTAL ERRORS ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=~\"actor-transaction.*handler-error\"})"
    }
   ]
  },
  {
   "title": "Kafka Processed Messages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=~\".*SnapshotPersisted-ProcessedMessagesCounter\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Transaction Latency Heatmap (ms)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(copernico_histograms_bucket{entity=~\"actor-transaction-.*_transaction-latency\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}} "
    }
   ]
  }
 ]
}